# Generated by Django 4.2.1 on 2023-06-03 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=125)),
                ('author', models.CharField(max_length=125)),
                ('isbn', models.CharField(max_length=125)),
                ('publisher', models.CharField(max_length=125)),
                ('number_of_page', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=3)),
                ('category', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('related_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_libraries.book')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
