# Generated by Django 4.2.1 on 2023-06-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_libraries', '0002_alter_book_author_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
