# Generated by Django 4.2.1 on 2023-06-05 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_libraries', '0003_book_image_url_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BorrowReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=125)),
                ('is_approved', models.BooleanField(default=False)),
                ('borrowed_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_libraries.borrowedbook')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
