# Generated by Django 4.2.1 on 2023-06-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_libraries', '0004_borrowedbook_is_borrowed_borrowreturnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowreturnrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowreturnrequest',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
