# Generated by Django 4.2.1 on 2023-06-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_libraries', '0005_borrowreturnrequest_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowreturnrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
