# Generated by Django 4.2.1 on 2023-06-05 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_libraries', '0007_alter_borrowreturnrequest_borrowed_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowreturnrequest',
            name='related_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public_libraries.book'),
        ),
    ]
